// let contaController = new ContaController();
let clienteController = new ClienteController();
// contaController.listar();
// const c1 = new Conta('1', 100);
// const c2 = new Conta('2', 400);
// const p1 = new Poupanca('2', 100);
// const cb1 = new ContaBonificada('3', 0);
// console.log('Conta: ' + c1.saldo);
// p1.atualizarSaldoAniversario();
// console.log('Poupanca: ' + p1.saldo);
// cb1.creditar(100);
// console.log('Conta Bonificada: ' + cb1.saldo);
// const cliente1 = new Cliente('Caio', '12345');
// const clientes = new Clientes();
// console.log('Cliente: ' + cliente1._nome + "  Criado");
// const cliente2 = new Cliente('Clods', '32123')
// console.log('Cliente: ' + cliente2._nome + "  Criado");
// clientes.inserir(cliente1);
// clientes.inserir(cliente2);
// console.log("Cliente: " + cliente1._nome + " foi inserido");
// console.log("Cliente: " + cliente2._nome + " foi inserido");
// var listados = clientes.listar();
// console.log(listados);
// clientes.pesquisar(cliente1._cpf);
// console.log("Cliente: " + cliente1._nome + " pesquisado");
// clientes.pesquisar(cliente2._cpf);
// console.log("Cliente: " + cliente2._nome + " pesquisado");
// clientes.remover(cliente1._cpf);
// console.log("Cliente: " + cliente1._nome + " foi de base");
